<?php
declare(strict_types=1);

use App\Forwarder\Config\ForwarderConfig;
use App\Forwarder\Http\ForwarderHttpClient;
use App\Forwarder\Http\ForwarderSessionClient;
use App\Forwarder\Http\SessionManager;
use App\Forwarder\Logging\ForwarderLogger;
use App\Forwarder\Services\LoginService;

require_once __DIR__ . '/bootstrap.php';
require_once __DIR__ . '/../../../../../configs/connectDB.php';

function pd_args(array $argv): array { $r=[]; foreach($argv as $a){ if(!is_string($a)||!str_starts_with($a,'--'))continue; $p=strpos($a,'='); if($p===false){$r[substr($a,2)]='1';}else{$r[substr($a,2,$p-2)]=substr($a,$p+1);} } return $r; }
function pd_arg(array $a,string ...$keys): string { foreach($keys as $k){ if(isset($a[$k])) return trim((string)$a[$k]); } return ''; }
function pd_out(array $p,int $c=0): void { echo json_encode($p,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT).PHP_EOL; exit($c); }
function pd_env(string $k,string $v): void { if($v==='')return; putenv($k.'='.$v); $_ENV[$k]=$v; }
function pd_base(string $u): string { $u=trim($u); if($u==='')return ''; $p=@parse_url($u); if(!is_array($p)||empty($p['scheme'])||empty($p['host'])) return rtrim($u,'/'); $b=strtolower($p['scheme']).'://'.$p['host']; if(isset($p['port']))$b.=':'.(int)$p['port']; return rtrim($b,'/'); }
function pd_norm_track(string $v): string { $v=trim($v); if(strlen($v)>=2 && (($v[0]==='"'&&substr($v,-1)==='"')||($v[0]==="'"&&substr($v,-1)==="'"))) $v=substr($v,1,-1); return trim($v); }
function pd_connector(mysqli $db,int $id): ?array { $s=$db->prepare('SELECT id,name,countries,base_url,auth_username,auth_password FROM connectors WHERE id=? LIMIT 1'); if(!$s)return null; $s->bind_param('i',$id); $s->execute(); $r=$s->get_result(); $row=$r?$r->fetch_assoc():null; $s->close(); return $row?:null; }
function pd_connector_key(array $connector,int $connectorId,string $country): string { $name=strtolower(trim((string)($connector['name']??''))); $cc=strtolower(trim($country)); if($connectorId===2 && str_contains($name,'colibri') && $cc==='az') return 'colibri_az'; $base=preg_replace('/[^a-z0-9]+/','_',strtolower(trim((string)($connector['name']??('connector_'.$connectorId))))); $base=trim((string)$base,'_'); return $cc!=='' ? $base.'_'.$cc : $base; }
function pd_cols(mysqli $db,string $t): array { $cols=[]; if($res=$db->query('SHOW COLUMNS FROM `'.str_replace('`','``',$t).'`')){while($row=$res->fetch_assoc())$cols[strtolower($row['Field'])]=1; $res->free();} return $cols; }
function pd_ensure_clients(mysqli $db): array { $adds=['client_phone'=>'ALTER TABLE connector_clients ADD COLUMN client_phone VARCHAR(64) NULL','client_payload_json'=>'ALTER TABLE connector_clients ADD COLUMN client_payload_json LONGTEXT NULL','details_synced_at'=>'ALTER TABLE connector_clients ADD COLUMN details_synced_at DATETIME NULL','details_source'=>'ALTER TABLE connector_clients ADD COLUMN details_source VARCHAR(64) NULL','details_last_error'=>'ALTER TABLE connector_clients ADD COLUMN details_last_error TEXT NULL']; $cols=pd_cols($db,'connector_clients'); foreach($adds as $c=>$sql){ if(!isset($cols[$c]) && @$db->query($sql)) $cols[$c]=1; } return pd_cols($db,'connector_clients'); }
function pd_upsert_client(mysqli $db,int $connectorId,array $connector,string $country,array $p,array $raw): void { if($connectorId<=0||trim((string)($p['client_id']??''))==='')return; $cols=pd_ensure_clients($db); $clientId=trim((string)$p['client_id']); $name=trim((string)($p['client_name']??$p['client']??'')); $email=trim((string)($p['client_email']??'')); $addr=trim((string)($p['client_address']??'')); $phone=trim((string)($p['client_phone']??'')); $payload=json_encode(['package'=>$p,'raw'=>$raw],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); $key=pd_connector_key($connector,$connectorId,$country); $forwarder=strtoupper(trim((string)($connector['name']??'COLIBRI'))); if($connectorId===2 && str_contains($forwarder,'COLIBRI')) $forwarder='COLIBRI'; $data=['connector_key'=>$key,'forwarder_name'=>$forwarder,'country_code'=>$country,'client_id'=>$clientId,'client_name'=>$name,'client_email'=>$email,'client_address'=>$addr,'client_phone'=>$phone,'client_payload_json'=>$payload,'details_synced_at'=>null,'details_source'=>'check-package','details_last_error'=>null,'first_seen_at'=>null,'last_seen_at'=>null]; if(isset($cols['connector_id'])) $data=['connector_id'=>$connectorId]+$data; $insert=[];$place=[];$types='';$vals=[];$updates=[]; foreach($data as $c=>$v){ if(!isset($cols[$c])) continue; $insert[]='`'.$c.'`'; if(in_array($c,['details_synced_at','first_seen_at','last_seen_at'],true)){ $place[]='NOW()'; } else { $place[]='?'; $types.=is_int($v)?'i':'s'; $vals[]=$v; } } foreach(['connector_key','forwarder_name','country_code','client_name','client_email','client_address','client_phone'] as $c){ if(isset($cols[$c])) $updates[]="`$c`=IF(VALUES(`$c`)<>'',VALUES(`$c`),`$c`)"; } foreach(['client_payload_json','details_source','details_last_error'] as $c){ if(isset($cols[$c])) $updates[]="`$c`=VALUES(`$c`)"; } if(isset($cols['details_synced_at'])) $updates[]='details_synced_at=NOW()'; if(isset($cols['last_seen_at'])) $updates[]='last_seen_at=NOW()'; $sql='INSERT INTO connector_clients ('.implode(',',$insert).') VALUES ('.implode(',',$place).') ON DUPLICATE KEY UPDATE '.implode(', ',$updates); $s=$db->prepare($sql); if($s){ if($types!=='') $s->bind_param($types,...$vals); $s->execute(); $s->close(); } }
function pd_pick(array $a,string $k): string { return trim((string)($a[$k]??'')); }
function pd_limit(string $v,int $default=100,int $max=1000): int { $n=(int)$v; if($n<=0)$n=$default; return max(1,min($n,$max)); }
function pd_init_client(array $args): ForwarderSessionClient { pd_env('DEV_COLIBRI_BASE_URL',pd_base(pd_arg($args,'base-url','base_url'))); pd_env('FORWARDER_BASE_URL',pd_base(pd_arg($args,'base-url','base_url'))); pd_env('DEV_COLIBRI_LOGIN',pd_arg($args,'login')); pd_env('FORWARDER_LOGIN',pd_arg($args,'login')); pd_env('DEV_COLIBRI_PASSWORD',pd_arg($args,'password')); pd_env('FORWARDER_PASSWORD',pd_arg($args,'password')); pd_env('FORWARDER_SESSION_FILE',pd_arg($args,'session-file','session_file')); $config=new ForwarderConfig(); if(!$config->isConfigured()) throw new RuntimeException('missing config (base-url/login/password)'); $logger=new ForwarderLogger('package-details'); $http=new ForwarderHttpClient($config); $session=new SessionManager($config->sessionCookieFile(),$config->sessionTtlSeconds()); $login=new LoginService($config,$http,$session,$logger); $client=new ForwarderSessionClient($config,$http,$session,$login,$logger); $client->ensureSession(); $client->requestWithSession('GET','/collector/packages',[],false); return $client; }
function pd_check_package(ForwarderSessionClient $client,string $track): array { $resp=$client->requestWithSession('POST','/collector/check-package',['number'=>$track],true); if((int)($resp['status_code']??0)===419){$client->requestWithSession('GET','/collector/packages',[],false); $resp=$client->requestWithSession('POST','/collector/check-package',['number'=>$track],true);} $raw=is_array($resp['json']??null)?$resp['json']:json_decode((string)($resp['body']??''),true); if(!is_array($raw)) throw new RuntimeException('invalid check-package response'); return $raw; }
function pd_package_out(array $raw): array { $pkg=is_array($raw['package']??null)?$raw['package']:[]; $out=[]; foreach(['internal_id','track','client_id','client','client_name','client_phone','client_address','category','invoice','invoice_usd','currency','invoice_doc','gross_weight','volume_weight','seller','seller_title','amount','flight_departure','flight_destination','flight_name','destination','title','description','client_comment'] as $k){$out[$k]=pd_pick($pkg,$k);} if(($out['client_id']??'')!=='' && empty($out['client_code'])) $out['client_code']='C'.$out['client_id']; return $out; }
function pd_latest_tracking(mysqli $db,string $clientId): string { $cols=pd_cols($db,'connector_report_colibri_az'); $order=isset($cols['id'])?'`id` DESC':(isset($cols['created_at'])?'`created_at` DESC':'1'); $sql="SELECT JSON_UNQUOTE(JSON_EXTRACT(payload_json, '$.tracking_number')) AS tracking_number FROM connector_report_colibri_az WHERE JSON_UNQUOTE(JSON_EXTRACT(payload_json, '$.client_id')) = ? AND JSON_UNQUOTE(JSON_EXTRACT(payload_json, '$.tracking_number')) IS NOT NULL AND JSON_UNQUOTE(JSON_EXTRACT(payload_json, '$.tracking_number')) <> '' ORDER BY $order LIMIT 1"; $s=$db->prepare($sql); if(!$s) throw new RuntimeException('failed to prepare latest tracking query: '.$db->error); $s->bind_param('s',$clientId); $s->execute(); $r=$s->get_result(); $row=$r?$r->fetch_assoc():null; $s->close(); return pd_norm_track((string)($row['tracking_number']??'')); }
function pd_update_client_details(mysqli $db,string $connectorKey,string $country,string $clientId,array $p,array $raw): bool { $cols=pd_ensure_clients($db); $set=[];$types='';$vals=[]; $phone=trim((string)($p['client_phone']??'')); $addr=trim((string)($p['client_address']??'')); if($phone!=='' && isset($cols['client_phone'])){$set[]='client_phone=?';$types.='s';$vals[]=$phone;} if($addr!=='' && isset($cols['client_address'])){$set[]='client_address=?';$types.='s';$vals[]=$addr;} if(isset($cols['client_payload_json'])){$set[]='client_payload_json=?';$types.='s';$vals[]=json_encode(['package'=>$p,'raw'=>$raw],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);} if(isset($cols['details_synced_at']))$set[]='details_synced_at=NOW()'; if(isset($cols['details_source'])){$set[]='details_source=?';$types.='s';$vals[]='check-package';} if(isset($cols['details_last_error']))$set[]='details_last_error=NULL'; if(!$set)return false; $sql='UPDATE connector_clients SET '.implode(', ',$set).' WHERE connector_key=? AND country_code=? AND client_id=? LIMIT 1'; $types.='sss'; array_push($vals,$connectorKey,$country,$clientId); $s=$db->prepare($sql); if(!$s)return false; $s->bind_param($types,...$vals); $s->execute(); $ok=$s->affected_rows>=0; $s->close(); return $ok; }
function pd_batch_missing_clients(mysqli $db,array $args,array $connector): void { $connectorKey='colibri_az'; $country='AZ'; $limit=pd_limit(pd_arg($args,'limit'),100,5000); $client=pd_init_client($args); $sql="SELECT client_id FROM connector_clients WHERE connector_key=? AND (client_address IS NULL OR client_address='' OR client_phone IS NULL OR client_phone='') ORDER BY client_id LIMIT ?"; $s=$db->prepare($sql); if(!$s) throw new RuntimeException('failed to prepare connector_clients query'); $s->bind_param('si',$connectorKey,$limit); $s->execute(); $res=$s->get_result(); $summary=['status'=>'ok','connector_id'=>2,'connector_key'=>$connectorKey,'source'=>'missing-clients','processed'=>0,'updated'=>0,'skipped'=>0,'errors'=>0]; while($row=$res->fetch_assoc()){ $clientId=trim((string)($row['client_id']??'')); if($clientId===''){ $summary['skipped']++; continue; } $summary['processed']++; try{ $track=pd_latest_tracking($db,$clientId); if($track===''){ $summary['skipped']++; continue; } $raw=pd_check_package($client,$track); if(strtolower((string)($raw['status']??''))==='error'){ $summary['errors']++; continue; } $out=pd_package_out($raw); if(pd_update_client_details($db,$connectorKey,$country,$clientId,$out,$raw)) $summary['updated']++; else $summary['skipped']++; }catch(Throwable $e){ $summary['errors']++; } } $s->close(); pd_out($summary); }

$args=pd_args($_SERVER['argv']??[]); $connectorId=(int)pd_arg($args,'connector-id','connector_id'); $track=pd_norm_track(pd_arg($args,'track','tracking-no','tracking_no','number'));
try{
 global $dbcnx; $connector=null; if($connectorId>0 && isset($dbcnx)&&$dbcnx instanceof mysqli){$connector=pd_connector($dbcnx,$connectorId);} $name=strtoupper(trim((string)($connector['name']??'')));
 if($connectorId===2 && pd_arg($args,'source')==='missing-clients'){ if(!isset($dbcnx)||!$dbcnx instanceof mysqli) pd_out(['status'=>'error','message'=>'missing database connection'],1); if($connector){ if(pd_arg($args,'base-url','base_url')==='')$args['base-url']=(string)$connector['base_url']; if(pd_arg($args,'login')==='')$args['login']=(string)$connector['auth_username']; if(pd_arg($args,'password')==='')$args['password']=(string)$connector['auth_password']; } if(pd_arg($args,'session-file','session_file')===''&&$connectorId>0)$args['session-file']=dirname(__DIR__,4).'/storage/forwarder_sessions/connector_'.$connectorId.'.cookie'; pd_batch_missing_clients($dbcnx,$args,$connector?:[]); }
 if($connector){ if(pd_arg($args,'base-url','base_url')==='')$args['base-url']=(string)$connector['base_url']; if(pd_arg($args,'login')==='')$args['login']=(string)$connector['auth_username']; if(pd_arg($args,'password')==='')$args['password']=(string)$connector['auth_password']; }
 if(str_contains($name,'ASER')) pd_out(['status'=>'error','message'=>'package details is not implemented for ASER'],1);
 if($track==='') pd_out(['status'=>'error','message'=>'missing --track'],2);
 if(pd_arg($args,'session-file','session_file')===''&&$connectorId>0)$args['session-file']=dirname(__DIR__,4).'/storage/forwarder_sessions/connector_'.$connectorId.'.cookie';
 $client=pd_init_client($args); $raw=pd_check_package($client,$track); $out=pd_package_out($raw);
 if(isset($dbcnx)&&$dbcnx instanceof mysqli && strtolower((string)($raw['status']??''))!=='error') pd_upsert_client($dbcnx,$connectorId,$connector?:[],strtoupper(substr(trim((string)($connector['countries']??'AZ')),0,2)),$out,$raw);
 pd_out(['status'=>'ok','connector_id'=>$connectorId,'tracking_no'=>$track,'package_exist'=>(bool)($raw['package_exist']??false),'client_exist'=>(bool)($raw['client_exist']??false),'package'=>$out,'raw'=>$raw]);
}catch(Throwable $e){ pd_out(['status'=>'error','message'=>$e->getMessage()],1); }
